language: go
services:
- docker
go:
- 1.11.x
cache:
  directories:
    - $HOME/.gocache
env:
  matrix:
  - GO111MODULE=on
  global:
  - GOCACHE=$HOME/.gocache
  - secure: TtgIxjXZ6modBXExBWECdxz/cjOjf17vg5c8sL6t9u74lzDTswhmkuTKQ5HbcIfPcvKlBZ5J1l96qDSgW5S58zu2X22VaBXRMgUoolXe8u1RfzFeU7E7vCzpeCIqLCDLn+1NAvwHIKNx2+ZcjFBiGRcG0ol8WfG6OgvQjr9RbmLLsJFLMVxDEpWRM9kFZMTv98ijPucpbCQOOC3B6aS2XvV863vKhrUTavm9AaWzUVdmlXqikWEjaRZVbm1IdI4qs6sqLVJd3kV1a55dFwJl0SI52/kfIIDOg8c40wPx0uFu4wSY6g5enS5CwDQZ7RSRNtL3khfOaD6zWOOnztUK2YOV85oaKK3rO95o4FOxjRNDRhF4Tb2mDmcoXBt17OvOvQ7hrOm0GNH7SA6nFpl/emjBqg3r3FsM/eZTQd6p2A3HseGHQ8wpOpQngyF9kUrgL03ChCpoc11EziFQIdkjNkLfG3OsUxF/Z8WD74IkU2bSjZ+por6U0If+xK0I3xEpozHuQCns8v6dRp31bRwl9Om8VqCHa7T38ypzFeuSzcFTk0Y+f3b0l5PsWwytA/gMfUGeGwNPU703NMI4HtbyiL82FGaMS0+gXpHsRXHzAk/e+mgM0Mx2kH94MWyrefyxW5bbZrbEKzVhExHfOAg8OM1KhnUIIU92t1nIR3Zy0EU=
  - secure: iN6+yZpQH+klM8wJ16Y9Jle6an5saQ2bzOdTREiZFIohaa1t4gHgr4fx2spJsOv/1B9iYSyWZ/UkSDZb8ZfwzI9SdvNbJ0Oj8C1o64/R5uK/mRYOhNK9jzEK3Yehj717Rtaeh1zZr9f6oDF99Sqp/so3PBHh94W4VENgRvHLHuasrkAFF0wZ87ri0dBpQrv82ngxA6nddIGVvM6WifrY+YbPr2Jbb5rL/SzACQgRp3Vlhnt4OXf3KoICm4hakOfLY2p82mncWImShxEOYCGeApm9WgB0/OM/ywBHU2yOHyfolP7M1WlxrlFqTJt9+fu1AqKp1rzQAdXPrkvs4MHImYWmMT6jGioVY5BY+1uZ6IW6YbTRUTrf29bT12Q5d+C6wIAx4I2ZPuK7tAORXZjpBprGEZ+tJy16Om6EKZydj4Vu+xtWAdS2FwVBUYK1CZGgVFq9eN87tFFohw7F5ACGmYHyLXItuqd3QE5K1Ky9tfJI7VVXBDfONO99kKgFtHi6crt+Vuf553gWNja9wlPKuclYiFNurJ7Gqj9Ml0Z5xKWD2We9i2UqNTV3u7NQ6wQ8oLkDXbz6fEvT3EmO3+Xh5qIG9xcUeArKV1IPDOB+KPkKEPHbfdcGHj5hmM8ojd03h6xsSTOUuCjtyh9Go2WolPaM9jTvkIW3GixXwd9ZBmI=
script:
- make test
- make linux_plugin
- docker build -t ozonru/filebeat-throttle-plugin:latest .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push ozonru/filebeat-throttle-plugin:latest
